### ISSUE TITLE
"Home" links to channel list, and "Channels" 404's

### ISSUE THREAD

**Issue by patcon** [ronnywang/g0v-slack-archive#1]
For logged out users. Seems that Home isn't necessary, and "Channels" should render what's currently the home page?

![screen shot 2018-10-11 at 12 36 28 am](https://user-images.githubusercontent.com/305339/46751644-b7eedc00-cced-11e8-8165-9a8514d95235.png)

If this sounds right, I'll make the PR

**Comment by ronnywang** [comment]
I removed the "Home" and changed the url of "Channels" from invalid "/index/channel" to "/".

Thanks
